const ACTIONS = {
  "LOGIN":"LOG_IN",
  "LOGOUT":"LOG_OUT",
  "GETSIGNATURES":"GET_ALL_SIGNATURES",
  "ADDSIGNATURE":"ADD_SIGNATURE",
  "ORDERSIGNATURE":"ORDER_SIGNATURE",
  "GETPARTS":"GET_SIGNATURE_PARTS",
  "GETGALLERY":"GET_ALTER_SIGNATURES",
  "DELETESIGNATURE":"DELETE_SIGNATURE"
};
